# Generates src/zigbounds.h: fixed-point brackets of the normal pdf around
# its chord in each ziggurat wedge, derived from the NumPy tables vendored
# in src/numpyzig/ziggurat_constants.h.
#
# zig_normal_slow() compares YL = floor(Y * L / 2^64) against R = 2^52 - rabs
# (Y the wedge word, L = 2^52 - ki[idx]). YL/L is the wedge uniform u and R/L
# is the chord value of the normalized pdf g(R) = (f(x) - fi[idx]) / Δf, so:
#
#   layers below the inflection (x < 1, f concave, g >= chord):
#     u < chord           => accept (needs no margin: chord <= g exactly)
#     u > chord + maxdev  => reject
#   layers above the inflection (x > 1, f convex, g <= chord): mirrored
#   the straddling layer needs both margins.
#
# The margins bound the exact real-valued curve, so the shortcut can only
# defer to the exp() fallback, never contradict it; SLACK covers the <= 2
# fixed-point flooring error plus double-rounding headroom.
#
# Run from the package root: Rscript dev/generate-zig-bounds.R

SLACK <- 4096

header <- "src/numpyzig/ziggurat_constants.h"
out_path <- "src/zigbounds.h"

h <- readLines(header)

grab <- function(name) {
  i <- grep(sprintf("^static const .*\\b%s\\[\\] = \\{", name), h)
  stopifnot(length(i) == 1L)
  j <- i + which(grepl("\\};\\s*$", h[(i + 1):length(h)]))[1]
  txt <- paste(h[(i + 1):j], collapse = " ")
  txt <- sub("\\};.*$", "", txt)
  toks <- regmatches(txt, gregexpr("0x[0-9a-fA-F]+|[0-9][-+.eE0-9]*", txt))[[1]]
  stopifnot(length(toks) == 256L)
  toks
}

hex2dbl <- function(s) {
  s <- sprintf("%016s", sub("^0x", "", s))
  vapply(s, function(z) {
    sum(strtoi(substring(z, c(1, 5, 9, 13), c(4, 8, 12, 16)), 16L) *
          2^c(48, 32, 16, 0))
  }, 0, USE.NAMES = FALSE)
}

ki <- hex2dbl(grab("ki_double"))
wi <- as.numeric(grab("wi_double"))
fi <- as.numeric(grab("fi_double"))

# sanity: fi[k] = exp(-x_k^2 / 2) for the layer edges (idx >= 1)
x_edge <- wi * 2^52
stopifnot(max(abs(fi[-1] - exp(-x_edge[-1]^2 / 2))) < 1e-15,
          fi[1] == 1)

# normalized curve minus chord for layer idx (0-based), rabs in [ki, 2^52)
dev_fun <- function(idx, rabs) {
  w <- wi[idx + 1]
  L <- 2^52 - ki[idx + 1]
  R <- 2^52 - rabs
  df <- fi[idx] - fi[idx + 1]        # fi[idx-1] - fi[idx], 0-based
  g <- (exp(-(rabs * w)^2 / 2) - fi[idx + 1]) / df
  g - R / L
}

max_dev <- function(idx, lo, hi, sign = 1) {
  f <- function(rabs) sign * dev_fun(idx, rabs)
  opt <- optimize(f, c(lo, hi), maximum = TRUE, tol = 1e-4)
  max(opt$objective, f(lo), f(hi), 0)
}

to_gap <- function(idx, dev) {
  L <- 2^52 - ki[idx + 1]
  gap <- ceiling(L * dev * (1 + 1e-9)) + SLACK
  stopifnot(gap < 2^53)
  gap
}

inflect <- which(x_edge[2:256] > 1)[1]  # 0-based idx of the straddling layer
stopifnot(x_edge[inflect] < 1, x_edge[inflect + 1] > 1)  # 1-based neighbours

gap <- numeric(256)
gap52_hi <- 0
for (idx in 1:255) {
  lo <- ki[idx + 1]
  hi <- 2^52
  if (idx < inflect) {
    gap[idx + 1] <- to_gap(idx, max_dev(idx, lo, hi, sign = 1))
  } else if (idx > inflect) {
    gap[idx + 1] <- to_gap(idx, max_dev(idx, lo, hi, sign = -1))
  } else {
    split <- 1 / wi[idx + 1]  # rabs where x = 1
    gap[idx + 1] <- to_gap(idx, max_dev(idx, split, hi, sign = -1))
    gap52_hi <- to_gap(idx, max_dev(idx, lo, split, sign = 1))
  }
}

# validation: on a dense grid the claimed one-sided bounds must hold.
# Because ki is a rounded integer, the curve can cross the chord by a few
# YL units at the rabs = ki end even away from the inflection; measured
# maximum is ~7.2, so the unmargined shortcut side can disagree with the
# exact test only in a band of relative measure ~ WRONG_SIDE_TOL * 2^-52
# per wedge draw -- the same order as double rounding in the exp() test.
WRONG_SIDE_TOL <- 16
for (idx in 1:255) {
  L <- 2^52 - ki[idx + 1]
  rabs <- seq(ki[idx + 1], 2^52, length.out = 20001)
  d <- dev_fun(idx, rabs) * L
  hi_gap <- if (idx == inflect) gap52_hi else gap[idx + 1]
  if (idx <= inflect) stopifnot(max(d) < hi_gap - SLACK / 2)
  if (idx >= inflect) stopifnot(max(-d) < gap[idx + 1] - SLACK / 2)
  if (idx < inflect) stopifnot(min(d) > -WRONG_SIDE_TOL)
  if (idx > inflect) stopifnot(max(d) < WRONG_SIDE_TOL)
}

fmt_u64 <- function(v) {
  vapply(v, function(z) {
    q <- as.integer((z %/% 2^c(48, 32, 16, 0)) %% 2^16)
    sprintf("UINT64_C(0x%04x%04x%04x%04x)", q[1], q[2], q[3], q[4])
  }, "")
}

lines <- c(
  "/* Generated by dev/generate-zig-bounds.R -- do not edit.",
  " *",
  " * Fixed-point brackets of the normal pdf around its chord in each",
  " * ziggurat wedge, derived from the NumPy tables in",
  " * src/numpyzig/ziggurat_constants.h. In layers below the inflection",
  " * (f concave) the gap bounds the curve above the chord and gates",
  " * rejection; above the inflection (f convex) it bounds the curve below",
  " * the chord and gates acceptance; the straddling layer uses both. */",
  "#ifndef RNGAT_ZIGBOUNDS_H",
  "#define RNGAT_ZIGBOUNDS_H",
  "",
  sprintf("#define RNGAT_ZIG_INFLECTION %d", inflect),
  sprintf("static const uint64_t rngat_zig_gap_hi52 = %s;",
          fmt_u64(gap52_hi)),
  "",
  "static const uint64_t rngat_zig_gap[] = {"
)
body <- vapply(seq(1, 256, by = 2), function(i) {
  paste0("    ", paste(fmt_u64(gap[i:min(i + 1, 256)]), collapse = ", "), ",")
}, "")
lines <- c(lines, body, "};", "", "#endif")
writeLines(lines, out_path)
cat("wrote", out_path, "| inflection layer:", inflect,
    "| gap52_hi:", gap52_hi, "\n")
cat("gap range (idx 1..255):", range(gap[2:256]), "\n")
