# Generated by dev/kat/emit_golden.R -- do not edit by hand.
#
# Cross-platform golden values. CI runs this on macOS, Windows, Linux
# (release + oldrel), clang23, gcc16, 32-bit i386 and musl; stateless
# generation promises every one of them produces identical values, and this
# is the only thing that actually checks it.
#
# These are a snapshot of zurand's own output, which is circular on its own.
# It is not circular in combination: test-kat.R pins the underlying bit
# stream against Random123's published vectors and an independent from-spec
# implementation, so what remains unverified is only the transforms, and
# that is exactly what these values fix in place.
#
# A failure here means either a real portability bug or a deliberate change
# to the stream. Regenerate only for the latter, and say so in the commit.
#
# Values are hex float literals because decimal ones are not portable: R on
# arm64 mis-rounds at least one 17-digit literal these tests need. Hex is
# exact, so a failure is always about zurand and never about the parser.

test_that("rng_uniform() is bit-stable", {
  expect_identical(rng_uniform(rng_key(42L), 12L),
    c(
      0x1.94892844f95b3p-1, 0x1.755a733c937bdp-1, 0x1.02e656ef8b9c5p-1,
      0x1.de7fc5b9fac18p-4, 0x1.28d0ec0331c84p-3, 0x1.217a5097cf953p-1,
      0x1.13922cd11f8b1p-1, 0x1.8f680c18ba557p-1, 0x1.0c3ba5f7a84d5p-1,
      0x1.51284d42ea72bp-1, 0x1.c5c477c80e57fp-1, 0x1.300957b62323p-5
    ))

  expect_identical(rng_uniform(rng_key(42L), 4L, min = -2, max = 5),
    c(
      0x1.c3f00678b45fap+1, 0x1.8d5e49aa0218ap+1, 0x1.8a26304668a32p+0,
      -0x1.2ea8197ea24b6p+0
    ))
})

test_that("rng_normal() is bit-stable, including the ziggurat slow paths", {
  expect_identical(rng_normal(rng_key(42L), 12L),
    c(
      0x1.eaf3a6731a5acp-3, 0x1.5da3eb05253b7p-1, 0x1.05605afe8dea1p-2,
      0x1.938a55bc3ab33p+0, 0x1.87e22300ef1bdp-1, -0x1.284c25bf4ee9ep+1,
      -0x1.f3260b407018p-1, -0x1.0b26fc6d6d0a6p+0, 0x1.bc0a4941cf33ep-1,
      0x1.406caf8b6ad26p+1, 0x1.a5b95a7214226p-5, -0x1.3d0a2d184f845p-1
    ))

  # Indices whose |z| >= 3.6542: the fast path cannot produce these, so they
  # pin the wedge and tail branches that most of the C code exists to serve.
  tail_idx <- c(1178L, 2172L, 4062L, 11756L, 13112L, 15279L, 28487L, 31217L)
  expect_identical(rng_normal(rng_key(42L), 200000L)[tail_idx],
    c(
      -0x1.dab829352c64fp+1, 0x1.e33d338a8b521p+1, 0x1.e15104edb253cp+1,
      0x1.e9dbc8aa84804p+1, -0x1.fe1f18f1827a2p+1, 0x1.f4489461bf7bap+1,
      -0x1.00d548d92c897p+2, -0x1.d6785e4c6308ap+1
    ))

  expect_identical(rng_normal(rng_key(42L), 4L, mean = 2, sd = 3),
    c(
      0x1.5c0daf3594f1p+1, 0x1.031d7821edf64p+2, 0x1.6204221f7537cp+1,
      0x1.aea7c04d2c066p+2
    ))
})

test_that("rng_integer() is bit-stable, including the rejection path", {
  expect_identical(rng_integer(rng_key(42L), 12L, min = 1L, max = 6L),
    c(
      2L, 2L, 1L, 5L, 5L, 2L, 3L, 3L, 2L, 2L, 4L, 1L
    ))

  # A near-maximal range makes Lemire rejection actually fire.
  expect_identical(rng_integer(rng_key(42L), 8L, min = 1L, max = 2000000000L),
    c(
      352578979L, 449361876L, 108978621L, 1398085695L, 1538485321L,
      638067389L, 977655369L, 980169362L
    ))

  # A range wider than 2^31: the offset above min no longer fits an int, so
  # this is the case that must not be computed as min + (int)offset.
  expect_identical(rng_integer(rng_key(42L), 8L, min = -2000000000L, max = 2000000000L),
    c(
      -1294842043L, -1101276249L, -1782042759L, 796171389L, 1076970642L,
      -723865223L, -44689263L, -39661276L
    ))
})

test_that("rng_fold() derives stable keys", {
  expect_identical(format(rng_fold(rng_key(42L), "layer1")),
    c(
      "rng_key[8dbacb9f407ebc3ae10ed1561177db53]"
    ))
  expect_identical(format(rng_fold(rng_key(42L), 7L)),
    c(
      "rng_key[a11aab0f92e75bb8303c089c13db8156]"
    ))
})

test_that("multi-key matrices are bit-stable", {
  # Column j must equal the single-key draw for key j; this pins the layout
  # as well as the values.
  expect_identical(as.vector(rng_normal(rng_key(42L, n = 3L), 4L)),
    c(
      0x1.eaf3a6731a5acp-3, 0x1.5da3eb05253b7p-1, 0x1.05605afe8dea1p-2,
      0x1.938a55bc3ab33p+0, -0x1.d3c185913a391p-1, -0x1.2e13522a66651p-3,
      0x1.62c9710da6bbap-2, 0x1.8280495aa9f7dp+0, -0x1.c34e037c85693p+0,
      -0x1.b5118f8401022p-3, -0x1.042b1290bfe1fp-1, 0x1.caf73ec4271a2p-2
    ))
})

test_that("the threefry4x64 engine is bit-stable", {
  # A second engine must be as reproducible as the first, and must produce a
  # different stream from the same seed -- a key records its engine.
  expect_identical(rng_uniform(rng_key(42L, engine = "threefry4x64"), 8L),
    c(
      0x1.5897a6b8bdd9cp-3, 0x1.4673851d43bccp-3, 0x1.d970ecb43db98p-4,
      0x1.7d92d9532840fp-1, 0x1.a645b682d7436p-2, 0x1.818fbe5879e7p-5,
      0x1.32c62654eca26p-2, 0x1.daf5d18731dc4p-3
    ))

  expect_identical(rng_normal(rng_key(42L, engine = "threefry4x64"), 8L),
    c(
      0x1.73fa9e85e3404p-2, -0x1.e2f195a626ee6p+0, -0x1.471f0b60d07e2p+1,
      0x1.9086f0d2cc325p-3, -0x1.7b3f06b84fd85p+0, -0x1.71054b72ccbdbp-1,
      -0x1.3eb001b919aa3p-3, -0x1.fa9e05411b387p-1
    ))

  expect_identical(rng_integer(rng_key(42L, engine = "threefry4x64"), 8L, min = 1L, max = 6L),
    c(
      3L, 4L, 6L, 3L, 3L, 6L, 3L, 6L
    ))

  expect_false(identical(rng_normal(rng_key(42L), 64L),
                         rng_normal(rng_key(42L, engine = "threefry4x64"), 64L)))
  expect_identical(attr(rng_key(1L, engine = "threefry4x64"), "engine"),
                   "threefry4x64")
})

test_that("the xoshiro256pp engine is bit-stable", {
  # Values either side of a 512-word chunk boundary, since that is where
  # this engine reseeds and the only place its indexing could go wrong.
  expect_identical(rng_uniform(rng_key(42L, engine = "xoshiro256pp"), 8L),
    c(
      0x1.4988189cff8bfp-1, 0x1.ab157a53c46f6p-2, 0x1.0602eb9773fe4p-3,
      0x1.b456575313855p-1, 0x1.6585e4082e9c2p-2, 0x1.a7c2a0cd00fd6p-2,
      0x1.f1001006a2aaep-2, 0x1.a661066328b8cp-3
    ))

  expect_identical(rng_normal(rng_key(42L, engine = "xoshiro256pp"), 8L),
    c(
      0x1.a16fec0c427a4p+0, -0x1.1e5ed0e26844fp+0, -0x1.53ee3709bad7fp-1,
      0x1.ea3a4df3d4c86p-3, -0x1.84eac07512cb3p-3, 0x1.23ee809a5d6a5p+0,
      0x1.e51aece65feebp-1, -0x1.511ace579518cp+0
    ))

  expect_identical(rng_uniform(rng_key(42L, engine = "xoshiro256pp"), 1030L)[508:520],
    c(
      0x1.01db1257ab559p-1, 0x1.48590d3ee5a24p-3, 0x1.569accb317091p-1,
      0x1.a1dd51f31c83p-5, 0x1.b15d07a312351p-1, 0x1.e3d20fcc2e735p-1,
      0x1.da275b5cff706p-2, 0x1.ca055dbb7302ep-2, 0x1.ecb7d0833eff8p-4,
      0x1.1e380dbe3af78p-4, 0x1.085021e3c048ap-2, 0x1.25b4b860936e1p-1,
      0x1.7e356443bfde2p-2
    ))

  expect_identical(rng_integer(rng_key(42L, engine = "xoshiro256pp"), 8L, min = 1L, max = 6L),
    c(
      3L, 1L, 4L, 2L, 5L, 3L, 3L, 1L
    ))

  expect_identical(as.character(rng_bits(rng_key(42L, engine = "xoshiro256pp"), 6L, bits = 64L)),
    c(
      "43c5f4cd83802dbd", "78da9ead113fe5a4", "299a3bb52451dd67",
      "5fbbf3fa2cd02aa7", "19f9ca1d2aa9841e", "7a0702166e468fd6"
    ))

  expect_false(identical(rng_normal(rng_key(42L), 64L),
                         rng_normal(rng_key(42L, engine = "xoshiro256pp"), 64L)))

  # A xoshiro key is a Philox key, so it folds with Philox: the derived key
  # words must equal what the same seed folds to under the philox engine,
  # with only the engine attribute differing. A two-way dispatch once sent
  # these down the threefry path; this pins the fix.
  fx <- rng_fold(rng_key(42L, engine = "xoshiro256pp"), "layer1")
  expect_identical(unclass(fx)[1L, ], unclass(rng_fold(rng_key(42L), "layer1"))[1L, ])
  expect_identical(attr(fx, "engine"), "xoshiro256pp")
  expect_identical(format(rng_fold(rng_key(42L, engine = "xoshiro256pp"), "layer1")),
    c(
      "rng_key[8dbacb9f407ebc3ae10ed1561177db53]"
    ))
})

test_that("draw i does not depend on n", {
  # The core counter-mode invariant, stated directly rather than implied.
  for (eng in c("philox4x64", "threefry4x64", "xoshiro256pp")) {
    key <- rng_key(99L, engine = eng)
    # 511/512/513 straddle the xoshiro chunk boundary.
    for (nn in c(3L, 17L, 64L, 257L, 511L, 512L, 513L, 1000L)) {
      expect_identical(rng_uniform(key, nn), rng_uniform(key, 1000L)[seq_len(nn)])
      expect_identical(rng_normal(key, nn), rng_normal(key, 1000L)[seq_len(nn)])
    }
  }
})
