# Generated by dev/kat/emit_golden.R -- do not edit by hand.
#
# Cross-platform golden values. CI runs this on macOS, Windows, Linux
# (release + oldrel), clang23, gcc16, 32-bit i386 and musl; stateless
# generation promises every one of them produces identical values, and this
# is the only thing that actually checks it.
#
# These are a snapshot of zurand's own output, which is circular on its own.
# It is not circular in combination: test-kat.R pins the underlying bit
# stream against Random123's published vectors and an independent from-spec
# implementation, so what remains unverified is only the transforms, and
# that is exactly what these values fix in place.
#
# A failure here means either a real portability bug or a deliberate change
# to the stream. Regenerate only for the latter, and say so in the commit.

test_that("rng_uniform() is bit-stable", {
  expect_identical(rng_uniform(rng_key(42L), 12L),
    c(
      0.79010892717331271, 0.72920570482687419, 0.50566360162866231,
      0.11682107197673053, 0.14492973694561695, 0.56538631299171482,
      0.53822460224889401, 0.78009069253782115, 0.5238925804916571,
      0.6585106033500997, 0.88626455609407617, 0.037113829909774743
    ))

  expect_identical(rng_uniform(rng_key(42L), 4L, min = -2, max = 5),
    c(
      3.5307624902131893, 3.104439933788119, 1.5396452114006363,
      -1.1822524961628864
    ))
})

test_that("rng_normal() is bit-stable, including the ziggurat slow paths", {
  expect_identical(rng_normal(rng_key(42L), 12L),
    c(
      0.23972253836408919, 0.6828912204533627, 0.2552503793590209,
      1.5763295731109792, 0.76539716135408009, -2.3148238357660622,
      -0.9748996273192887, -1.0435636298325703, 0.86726597717606757,
      2.503316824984398, 0.051479984904862428, -0.61921826287994775
    ))

  # Indices whose |z| >= 3.6542: the fast path cannot produce these, so they
  # pin the wedge and tail branches that most of the C code exists to serve.
  tail_idx <- c(1178L, 2172L, 4062L, 11756L, 13112L, 15279L, 28487L, 31217L)
  expect_identical(rng_normal(rng_key(42L), 200000L)[tail_idx],
    c(
      -3.7087451467166725, 3.7753052164540724, 3.7602850113513835,
      3.8270197708707219, -3.9853240184065308, 3.9084649541173038,
      -4.0130178566779682, -3.6755483506186168
    ))

  expect_identical(rng_normal(rng_key(42L), 4L, mean = 2, sd = 3),
    c(
      2.7191676150922675, 4.0486736613600876, 2.7657511380770625,
      6.7289887193329374
    ))
})

test_that("rng_integer() is bit-stable, including the rejection path", {
  expect_identical(rng_integer(rng_key(42L), 12L, min = 1L, max = 6L),
    c(
      2L, 2L, 1L, 5L, 5L, 2L, 3L, 3L, 2L, 2L, 4L, 1L
    ))

  # A near-maximal range makes Lemire rejection actually fire.
  expect_identical(rng_integer(rng_key(42L), 8L, min = 1L, max = 2000000000L),
    c(
      352578979L, 449361876L, 108978621L, 1398085695L, 1538485321L,
      638067389L, 977655369L, 980169362L
    ))
})

test_that("rng_fold() derives stable keys", {
  expect_identical(format(rng_fold(rng_key(42L), "layer1")),
    c(
      "rng_key[8dbacb9f407ebc3ae10ed1561177db53]"
    ))
  expect_identical(format(rng_fold(rng_key(42L), 7L)),
    c(
      "rng_key[a11aab0f92e75bb8303c089c13db8156]"
    ))
})

test_that("multi-key matrices are bit-stable", {
  # Column j must equal the single-key draw for key j; this pins the layout
  # as well as the values.
  expect_identical(as.vector(rng_normal(rng_key(42L, n = 3L), 4L)),
    c(
      0.23972253836408919, 0.6828912204533627, 0.2552503793590209,
      1.5763295731109792, -0.91358582876010719, -0.1474977893056342,
      0.3464715637762158, 1.5097699972484115, -1.7629091433531456,
      -0.21341240045160342, -0.50814111725771116, 0.44820879051419571
    ))
})

test_that("draw i does not depend on n", {
  # The core counter-mode invariant, stated directly rather than implied.
  key <- rng_key(99L)
  for (nn in c(3L, 17L, 64L, 257L, 1000L)) {
    expect_identical(rng_uniform(key, nn), rng_uniform(key, 1000L)[seq_len(nn)])
    expect_identical(rng_normal(key, nn), rng_normal(key, 1000L)[seq_len(nn)])
  }
})
