# Generated by dev/kat/emit_kat.py -- do not edit by hand.
#
# Known-answer tests. These pin the *bit stream*: that zurand really is
# philox4x64-10, and that its counter and key plumbing put the bits where
# we think. Expected values come from two independent places, never from
# zurand itself:
#
#   1. Random123's own published tests/kat_vectors, for the one counter
#      zurand can reach through its public API (all words zero).
#   2. A from-spec Philox written in Python (dev/kat/philox_ref.py), which
#      is validated against all six philox4x64 rows of kat_vectors -- both
#      round counts, including the two counters zurand cannot reach --
#      before it is trusted to generate anything here.

# A key is an opaque S3 object;;these tests reach past that on purpose, to
# set the exact key words a reference vector requires. Package code must
# not do this.
raw_key <- function(words) {
  structure(matrix(as.integer(words), nrow = 1L),
            class = "rng_key", engine = "philox4x64")
}

test_that("rng_bits() reproduces Random123's published vector", {
  # tests/kat_vectors: philox4x64 10 <ctr=0 x4> <key=0 x2>
  # zurand block b uses ctr = {b, 0, 0, 0} and purpose BITS = 0, so a zero
  # key at block 0 is exactly this vector.
  expect_identical(
    as.character(rng_bits(raw_key(rep(0L, 4L)), 4L, bits = 64L)),
    c("16554d9eca36314c", "db20fe9d672d0fdc",
      "d7e772cee186176b", "7e68b68aec7ba23b"))
})

test_that("rng_bits() matches an independent Philox across keys and blocks", {
  # 3 blocks x 4 words per seed, so this covers the counter advancing,
  # not just block 0.

  # seed 42  ->  k0 = bdd732262feb6e95, k1 = 28efe333b266f103
  expect_identical(
    as.character(rng_bits(rng_key(42L), 12L, bits = 64L)),
    c(
      "c0e6592123d7a06c", "0c89edc8a3ba5356", "6eb27f65d390675b",
      "73af8b93bd67b8f2", "ef5187b4d040f49c", "aa17f09827274d47",
      "c4d0f5ed62f74c02", "37eb0f6f53bbf73b", "8415bb3dec46e764",
      "993e7bbaedc7bc9e", "bd02319acb6f3934", "2f6f30d99a1faa27"
    ))

  # seed 1  ->  k0 = 910a2dec89025cc1, k1 = beeb8da1658eec67
  expect_identical(
    as.character(rng_bits(rng_key(1L), 12L, bits = 64L)),
    c(
      "19078d6eed2ba664", "0af0eeb0cc695abb", "2f3332a64d618318",
      "9c8f286371b85d0b", "ace918e832800829", "01b0dbae3278fa01",
      "2f753f94cfb850ea", "c9871c9102292e7c", "d20a5e1f7e02f4a1",
      "dcb8076aff638e4f", "2d0248abc1ef4b11", "212ae9265107732c"
    ))

  # seed 2026  ->  k0 = db9c559891948d23, k1 = 78bc927ded35455d
  expect_identical(
    as.character(rng_bits(rng_key(2026L), 12L, bits = 64L)),
    c(
      "b2fd63df6e08d008", "27ec210dbef4c866", "aef1b7a014abcaf6",
      "4fc706007c9294de", "c2c036d9dc9703f3", "bf3638e775d28826",
      "d42284f7f13fc193", "ee7762ef6ad6a68d", "0b801e6d0a70d5b3",
      "5918325c9d507503", "79984b40936dec5c", "dda6110eadf125fd"
    ))
})

test_that("the threefry4x64 engine really is threefry4x64-13", {
  # Same argument as above, with one extra link. A zurand key stores 128
  # bits and threefry4x64 wants 256, so src/zurand.c derives the upper
  # half by xor with Threefry's own Weyl constants. These expectations run
  # that derivation through the independent reference too, so the test
  # covers the key expansion and not only the cipher.

  # seed 42  ->  derived key bdd732262feb6e95 28efe333b266f103
  #                          23e04b9f50a11280 93884db636ac5638
  expect_identical(
    as.character(rng_bits(rng_key(42L, engine = "threefry4x64"), 12L,
                          bits = 64L)),
    c(
      "34c97278d79b0d7b", "0c2eef287dc2f066", "c2b878ac91de3e96",
      "d9d98a208ae031cc", "b9eb27c2c2aeb507", "30fe88a576ae91e0",
      "99a286e4fab778df", "9eaa661d56524df0", "dade34f23716ed4f",
      "72185b392dbcc061", "56f468cb20f7c549", "638e93e206be3712"
    ))

  # seed 1  ->  derived key 910a2dec89025cc1 beeb8da1658eec67
  #                          0f3d5455f64820d4 058c2324e1444b5c
  expect_identical(
    as.character(rng_bits(rng_key(1L, engine = "threefry4x64"), 12L,
                          bits = 64L)),
    c(
      "32df86fb3aafc23e", "5f2ebc6bf807184f", "4def0762be0da85c",
      "94d30c986dbb5e30", "b89e1eb654a5b06b", "4ee849b5804cd42f",
      "28cb443e6f09ed34", "104caa2c734225c5", "34620cf838ee1f00",
      "0966580573df3d67", "38dbfc75d794c17d", "5b219df0ca3ca524"
    ))

  # seed 2026  ->  derived key db9c559891948d23 78bc927ded35455d
  #                          45ab2c21eedef136 c3db3cf869ffe266
  expect_identical(
    as.character(rng_bits(rng_key(2026L, engine = "threefry4x64"), 12L,
                          bits = 64L)),
    c(
      "7a6af12555eaf393", "b6046174c5b150ff", "a88552da1885b93f",
      "e1b969331557065e", "057369fcfaecb8b3", "0d315b9a0d94fdff",
      "8b2f0c5bb847cb40", "974faccefcc76fdb", "0381d0bf894c9d2c",
      "899a8d1fd4711838", "866409fddb46bd74", "34b98d664f4c30d0"
    ))
})

test_that("the xoshiro256pp engine is Philox-seeded xoshiro256++", {
  # dev/kat/xoshiro_ref.py is validated against Vigna's own reference C
  # from a fixed state before generating anything. These expectations then
  # run zurand's chunk seeding -- Philox at {chunk, 0, purpose, 0}, with the
  # all-zero guard -- through the independent Philox reference, so the seed
  # derivation is covered and not only the recurrence.

  # seed 42, chunk 0
  expect_identical(
    as.character(rng_bits(rng_key(42L, engine = "xoshiro256pp"), 12L,
                          bits = 64L)),
    c(
      "43c5f4cd83802dbd", "78da9ead113fe5a4", "299a3bb52451dd67",
      "5fbbf3fa2cd02aa7", "19f9ca1d2aa9841e", "7a0702166e468fd6",
      "6375abd361bd67b0", "cd5550b6f84b7143", "28c4819c67aee065",
      "4797aa23e3c82513", "5230501d0813e217", "83048653310e7dbe"
    ))

  # seed 1, chunk 0
  expect_identical(
    as.character(rng_bits(rng_key(1L, engine = "xoshiro256pp"), 12L,
                          bits = 64L)),
    c(
      "70a59c7d3ebaa6be", "acb6925e51f278c2", "88c0b3ef43baddf7",
      "d2984b97aa87f48a", "4477c0504ee3e82c", "b0a2dfb8e45edf48",
      "01c0c612baf2e34a", "b286c333f4d231a1", "b7614b70315703de",
      "e51acc1217b946ae", "614c328eb022d89c", "3b908773b1b8ae77"
    ))

  # seed 2026, chunk 0
  expect_identical(
    as.character(rng_bits(rng_key(2026L, engine = "xoshiro256pp"), 12L,
                          bits = 64L)),
    c(
      "4175b5c953f366e5", "df902ff6ad22f930", "5f1463f89ce46b24",
      "206cab7051d620e3", "6df7825e2538a28c", "0e4caaa3a788c13a",
      "e1be9dbc45c0b6e7", "f04370075bc595ab", "bd49e8155275b13b",
      "e69d3355426afa33", "a71572e9e93c2284", "e7c7d585b614c377"
    ))

  # seed 42, words 510..515: the last two of chunk 0 and the first four of
  # chunk 1. This is where a reseeding engine can go wrong and nowhere else.
  expect_identical(
    as.character(rng_bits(rng_key(42L, engine = "xoshiro256pp"), 516L,
                          bits = 64L))[511:516],
    c(
      "9cd34d657f47ae4e", "bb4c81a002ded4d6", "78b32993e2c6421d",
      "7fef2abfe002c6a7", "c970545f205ba1b1", "455f32d504bd369d"
    ))
})

test_that("rng_bits(32) is the low half of the 64-bit stream", {
  # The two widths must be views of one stream, not two streams.
  key <- rng_key(42L)
  hex <- as.character(rng_bits(key, 8L, bits = 64L))
  # strtoi() returns NA above 2^31, so fold two 16-bit halves in double
  # arithmetic instead of parsing all 8 low hex digits at once.
  lo <- strtoi(substr(hex, 9L, 12L), 16L) * 65536 +
        strtoi(substr(hex, 13L, 16L), 16L)
  expect_equal(rng_bits(key, 8L), lo)
})
