# Generated by dev/kat/emit_kat.py -- do not edit by hand.
#
# Known-answer tests. These pin the *bit stream*: that zurand really is
# philox4x64-10, and that its counter and key plumbing put the bits where
# we think. Expected values come from two independent places, never from
# zurand itself:
#
#   1. Random123's own published tests/kat_vectors, for the one counter
#      zurand can reach through its public API (all words zero).
#   2. A from-spec Philox written in Python (dev/kat/philox_ref.py), which
#      is validated against all six philox4x64 rows of kat_vectors -- both
#      round counts, including the two counters zurand cannot reach --
#      before it is trusted to generate anything here.

# A key is an opaque S3 object;;these tests reach past that on purpose, to
# set the exact key words a reference vector requires. Package code must
# not do this.
raw_key <- function(words) {
  structure(matrix(as.integer(words), nrow = 1L),
            class = "rng_key", engine = "philox4x64")
}

test_that("rng_bits() reproduces Random123's published vector", {
  # tests/kat_vectors: philox4x64 10 <ctr=0 x4> <key=0 x2>
  # zurand block b uses ctr = {b, 0, 0, 0} and purpose BITS = 0, so a zero
  # key at block 0 is exactly this vector.
  expect_identical(
    as.character(rng_bits(raw_key(rep(0L, 4L)), 4L, bits = 64L)),
    c("16554d9eca36314c", "db20fe9d672d0fdc",
      "d7e772cee186176b", "7e68b68aec7ba23b"))
})

test_that("rng_bits() matches an independent Philox across keys and blocks", {
  # 3 blocks x 4 words per seed, so this covers the counter advancing,
  # not just block 0.

  # seed 42  ->  k0 = bdd732262feb6e95, k1 = 28efe333b266f103
  expect_identical(
    as.character(rng_bits(rng_key(42L), 12L, bits = 64L)),
    c(
      "c0e6592123d7a06c", "0c89edc8a3ba5356", "6eb27f65d390675b",
      "73af8b93bd67b8f2", "ef5187b4d040f49c", "aa17f09827274d47",
      "c4d0f5ed62f74c02", "37eb0f6f53bbf73b", "8415bb3dec46e764",
      "993e7bbaedc7bc9e", "bd02319acb6f3934", "2f6f30d99a1faa27"
    ))

  # seed 1  ->  k0 = 910a2dec89025cc1, k1 = beeb8da1658eec67
  expect_identical(
    as.character(rng_bits(rng_key(1L), 12L, bits = 64L)),
    c(
      "19078d6eed2ba664", "0af0eeb0cc695abb", "2f3332a64d618318",
      "9c8f286371b85d0b", "ace918e832800829", "01b0dbae3278fa01",
      "2f753f94cfb850ea", "c9871c9102292e7c", "d20a5e1f7e02f4a1",
      "dcb8076aff638e4f", "2d0248abc1ef4b11", "212ae9265107732c"
    ))

  # seed 2026  ->  k0 = db9c559891948d23, k1 = 78bc927ded35455d
  expect_identical(
    as.character(rng_bits(rng_key(2026L), 12L, bits = 64L)),
    c(
      "b2fd63df6e08d008", "27ec210dbef4c866", "aef1b7a014abcaf6",
      "4fc706007c9294de", "c2c036d9dc9703f3", "bf3638e775d28826",
      "d42284f7f13fc193", "ee7762ef6ad6a68d", "0b801e6d0a70d5b3",
      "5918325c9d507503", "79984b40936dec5c", "dda6110eadf125fd"
    ))
})

test_that("rng_bits(32) is the low half of the 64-bit stream", {
  # The two widths must be views of one stream, not two streams.
  key <- rng_key(42L)
  hex <- as.character(rng_bits(key, 8L, bits = 64L))
  # strtoi() returns NA above 2^31, so fold two 16-bit halves in double
  # arithmetic instead of parsing all 8 low hex digits at once.
  lo <- strtoi(substr(hex, 9L, 12L), 16L) * 65536 +
        strtoi(substr(hex, 13L, 16L), 16L)
  expect_equal(rng_bits(key, 8L), lo)
})
