# Regenerates tests/testthat/test-golden.R. Run on the M1 (the reference
# platform) after any *intentional* change to the output stream:
#   R CMD INSTALL . && Rscript dev/kat/emit_golden.R
library(zurand)

# Hex float literals, not decimal. A decimal literal has to go through the
# platform's decimal-to-binary parser, and that parser is not always
# correctly rounded: "0.79010892717331271" lies above the midpoint of two
# adjacent doubles, so it must round up, and R on arm64 rounds it down -- one
# ulp, on a value zurand computes identically on every platform. A test for
# bit-stability cannot be built on a representation that is itself unstable.
# R parses %a literals exactly, verified over the full set below.
g <- function(x) sprintf("%a", x)

wrap <- function(xs, indent = "      ", width = 74) {
  out <- character(0); line <- indent
  for (i in seq_along(xs)) {
    piece <- paste0(xs[[i]], if (i < length(xs)) "," else "")
    if (nchar(line) + nchar(piece) + 1 > width) { out <- c(out, sub(" +$", "", line)); line <- indent }
    line <- paste0(line, piece, " ")
  }
  c(out, sub(" +$", "", line))
}
blk <- function(call, vals, quote = FALSE) {
  v <- if (quote) paste0('"', vals, '"') else vals
  c(paste0("  expect_identical(", call, ","), "    c(", wrap(v), "    ))")
}

key <- rng_key(42L)
keys <- rng_key(42L, n = 3L)
tkey <- rng_key(42L, engine = "threefry4x64")
xkey <- rng_key(42L, engine = "xoshiro256pp")
z <- rng_normal(key, 200000L)
tail_i <- which(abs(z) >= 3.6542)[1:8]

L <- c(
"# Generated by dev/kat/emit_golden.R -- do not edit by hand.",
"#",
"# Cross-platform golden values. CI runs this on macOS, Windows, Linux",
"# (release + oldrel), clang23, gcc16, 32-bit i386 and musl; stateless",
"# generation promises every one of them produces identical values, and this",
"# is the only thing that actually checks it.",
"#",
"# These are a snapshot of zurand's own output, which is circular on its own.",
"# It is not circular in combination: test-kat.R pins the underlying bit",
"# stream against Random123's published vectors and an independent from-spec",
"# implementation, so what remains unverified is only the transforms, and",
"# that is exactly what these values fix in place.",
"#",
"# A failure here means either a real portability bug or a deliberate change",
"# to the stream. Regenerate only for the latter, and say so in the commit.",
"#",
"# Values are hex float literals because decimal ones are not portable: R on",
"# arm64 mis-rounds at least one 17-digit literal these tests need. Hex is",
"# exact, so a failure is always about zurand and never about the parser.",
"",
"test_that(\"rng_uniform() is bit-stable\", {",
  blk("rng_uniform(rng_key(42L), 12L)", g(rng_uniform(key, 12L))),
"",
  blk("rng_uniform(rng_key(42L), 4L, min = -2, max = 5)",
      g(rng_uniform(key, 4L, min = -2, max = 5))),
"})",
"",
"test_that(\"rng_normal() is bit-stable, including the ziggurat slow paths\", {",
  blk("rng_normal(rng_key(42L), 12L)", g(rng_normal(key, 12L))),
"",
"  # Indices whose |z| >= 3.6542: the fast path cannot produce these, so they",
"  # pin the wedge and tail branches that most of the C code exists to serve.",
  paste0("  tail_idx <- c(", paste(tail_i, collapse = "L, "), "L)"),
  blk("rng_normal(rng_key(42L), 200000L)[tail_idx]", g(z[tail_i])),
"",
  blk("rng_normal(rng_key(42L), 4L, mean = 2, sd = 3)",
      g(rng_normal(key, 4L, mean = 2, sd = 3))),
"})",
"",
"test_that(\"rng_integer() is bit-stable, including the rejection path\", {",
  blk("rng_integer(rng_key(42L), 12L, min = 1L, max = 6L)",
      paste0(rng_integer(key, 12L, min = 1L, max = 6L), "L")),
"",
"  # A near-maximal range makes Lemire rejection actually fire.",
  blk("rng_integer(rng_key(42L), 8L, min = 1L, max = 2000000000L)",
      paste0(rng_integer(key, 8L, min = 1L, max = 2000000000L), "L")),
"})",
"",
"test_that(\"rng_fold() derives stable keys\", {",
  blk("format(rng_fold(rng_key(42L), \"layer1\"))",
      format(rng_fold(key, "layer1")), quote = TRUE),
  blk("format(rng_fold(rng_key(42L), 7L))",
      format(rng_fold(key, 7L)), quote = TRUE),
"})",
"",
"test_that(\"multi-key matrices are bit-stable\", {",
"  # Column j must equal the single-key draw for key j; this pins the layout",
"  # as well as the values.",
  blk("as.vector(rng_normal(rng_key(42L, n = 3L), 4L))",
      g(as.vector(rng_normal(keys, 4L)))),
"})",
"",
"test_that(\"the threefry4x64 engine is bit-stable\", {",
"  # A second engine must be as reproducible as the first, and must produce a",
"  # different stream from the same seed -- a key records its engine.",
  blk("rng_uniform(rng_key(42L, engine = \"threefry4x64\"), 8L)",
      g(rng_uniform(tkey, 8L))),
"",
  blk("rng_normal(rng_key(42L, engine = \"threefry4x64\"), 8L)",
      g(rng_normal(tkey, 8L))),
"",
  blk("rng_integer(rng_key(42L, engine = \"threefry4x64\"), 8L, min = 1L, max = 6L)",
      paste0(rng_integer(tkey, 8L, min = 1L, max = 6L), "L")),
"",
"  expect_false(identical(rng_normal(rng_key(42L), 64L),",
"                         rng_normal(rng_key(42L, engine = \"threefry4x64\"), 64L)))",
"  expect_identical(attr(rng_key(1L, engine = \"threefry4x64\"), \"engine\"),",
"                   \"threefry4x64\")",
"})",
"",
"test_that(\"the xoshiro256pp engine is bit-stable\", {",
"  # Values either side of a 512-word chunk boundary, since that is where",
"  # this engine reseeds and the only place its indexing could go wrong.",
  blk("rng_uniform(rng_key(42L, engine = \"xoshiro256pp\"), 8L)",
      g(rng_uniform(xkey, 8L))),
"",
  blk("rng_normal(rng_key(42L, engine = \"xoshiro256pp\"), 8L)",
      g(rng_normal(xkey, 8L))),
"",
  blk("rng_uniform(rng_key(42L, engine = \"xoshiro256pp\"), 1030L)[508:520]",
      g(rng_uniform(xkey, 1030L)[508:520])),
"",
  blk("rng_integer(rng_key(42L, engine = \"xoshiro256pp\"), 8L, min = 1L, max = 6L)",
      paste0(rng_integer(xkey, 8L, min = 1L, max = 6L), "L")),
"",
  blk("as.character(rng_bits(rng_key(42L, engine = \"xoshiro256pp\"), 6L, bits = 64L))",
      as.character(rng_bits(xkey, 6L, bits = 64L)), quote = TRUE),
"",
"  expect_false(identical(rng_normal(rng_key(42L), 64L),",
"                         rng_normal(rng_key(42L, engine = \"xoshiro256pp\"), 64L)))",
"})",
"",
"test_that(\"draw i does not depend on n\", {",
"  # The core counter-mode invariant, stated directly rather than implied.",
"  for (eng in c(\"philox4x64\", \"threefry4x64\", \"xoshiro256pp\")) {",
"    key <- rng_key(99L, engine = eng)",
"    # 511/512/513 straddle the xoshiro chunk boundary.",
"    for (nn in c(3L, 17L, 64L, 257L, 511L, 512L, 513L, 1000L)) {",
"      expect_identical(rng_uniform(key, nn), rng_uniform(key, 1000L)[seq_len(nn)])",
"      expect_identical(rng_normal(key, nn), rng_normal(key, 1000L)[seq_len(nn)])",
"    }",
"  }",
"})")

writeLines(L, "tests/testthat/test-golden.R")
cat("wrote tests/testthat/test-golden.R  (", length(L), " lines )\n", sep = "")
