import sys, os, io, contextlib
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
with contextlib.redirect_stdout(io.StringIO()):      # silence the self-validation
    from philox_ref import philox4x64
    from threefry_ref import threefry4x64
def u32(i): return i & 0xffffffff
CASES = {
  42:   [803958421,-1109970394,-1301876477,686809907],
  1:    [-1996333887,-1861603860,1703865447,-1091859039],
  2026: [-1852535517,-610511464,-315275939,2025624189],
}
NW = 12   # 3 blocks
def rvec(xs, indent):
    out, line = [], indent
    for i, x in enumerate(xs):
        piece = '"%s"' % x + ("," if i < len(xs)-1 else "")
        if len(line) + len(piece) + 1 > 76:
            out.append(line.rstrip()); line = indent
        line += piece + " "
    out.append(line.rstrip())
    return "\n".join(out)

L = []
L.append('# Generated by dev/kat/emit_kat.py -- do not edit by hand.')
L.append('#')
L.append('# Known-answer tests. These pin the *bit stream*: that zurand really is')
L.append('# philox4x64-10, and that its counter and key plumbing put the bits where')
L.append('# we think. Expected values come from two independent places, never from')
L.append('# zurand itself:')
L.append('#')
L.append('#   1. Random123\'s own published tests/kat_vectors, for the one counter')
L.append('#      zurand can reach through its public API (all words zero).')
L.append('#   2. A from-spec Philox written in Python (dev/kat/philox_ref.py), which')
L.append('#      is validated against all six philox4x64 rows of kat_vectors -- both')
L.append('#      round counts, including the two counters zurand cannot reach --')
L.append('#      before it is trusted to generate anything here.')
L.append('')
L.append('# A key is an opaque S3 object;;these tests reach past that on purpose, to')
L.append('# set the exact key words a reference vector requires. Package code must')
L.append('# not do this.')
L.append('raw_key <- function(words) {')
L.append('  structure(matrix(as.integer(words), nrow = 1L),')
L.append('            class = "rng_key", engine = "philox4x64")')
L.append('}')
L.append('')
L.append('test_that("rng_bits() reproduces Random123\'s published vector", {')
L.append('  # tests/kat_vectors: philox4x64 10 <ctr=0 x4> <key=0 x2>')
L.append('  # zurand block b uses ctr = {b, 0, 0, 0} and purpose BITS = 0, so a zero')
L.append('  # key at block 0 is exactly this vector.')
L.append('  expect_identical(')
L.append('    as.character(rng_bits(raw_key(rep(0L, 4L)), 4L, bits = 64L)),')
L.append('    c("16554d9eca36314c", "db20fe9d672d0fdc",')
L.append('      "d7e772cee186176b", "7e68b68aec7ba23b"))')
L.append('})')
L.append('')
L.append('test_that("rng_bits() matches an independent Philox across keys and blocks", {')
L.append('  # 3 blocks x 4 words per seed, so this covers the counter advancing,')
L.append('  # not just block 0.')
for seed, w in CASES.items():
    k = [u32(w[0]) | (u32(w[1]) << 32), u32(w[2]) | (u32(w[3]) << 32)]
    vals = []
    for b in range(3):
        vals += ['%016x' % x for x in philox4x64([b,0,0,0], k, 10)]
    L.append('')
    L.append('  # seed %d  ->  k0 = %016x, k1 = %016x' % (seed, k[0], k[1]))
    L.append('  expect_identical(')
    L.append('    as.character(rng_bits(rng_key(%dL), %dL, bits = 64L)),' % (seed, NW))
    L.append('    c(')
    L.append(rvec(vals, '      '))
    L.append('    ))')
L.append('})')
L.append('')
L.append('test_that("the threefry4x64 engine really is threefry4x64-13", {')
L.append('  # Same argument as above, with one extra link. A zurand key stores 128')
L.append('  # bits and threefry4x64 wants 256, so src/zurand.c derives the upper')
L.append("  # half by xor with Threefry's own Weyl constants. These expectations run")
L.append('  # that derivation through the independent reference too, so the test')
L.append('  # covers the key expansion and not only the cipher.')
for seed, w in CASES.items():
    k = [u32(w[0]) | (u32(w[1]) << 32), u32(w[2]) | (u32(w[3]) << 32)]
    tk = [k[0], k[1], k[0] ^ 0x9e3779b97f4a7c15, k[1] ^ 0xbb67ae8584caa73b]
    vals = []
    for b in range(3):
        vals += ['%016x' % x for x in threefry4x64([b,0,0,0], tk, 13)]
    L.append('')
    L.append('  # seed %d  ->  derived key %s' % (seed, " ".join("%016x" % x for x in tk[:2])))
    L.append('  #                          %s' % " ".join("%016x" % x for x in tk[2:]))
    L.append('  expect_identical(')
    L.append('    as.character(rng_bits(rng_key(%dL, engine = "threefry4x64"), %dL,' % (seed, NW))
    L.append('                          bits = 64L)),')
    L.append('    c(')
    L.append(rvec(vals, '      '))
    L.append('    ))')
L.append('})')
L.append('')
L.append('test_that("rng_bits(32) is the low half of the 64-bit stream", {')
L.append('  # The two widths must be views of one stream, not two streams.')
L.append('  key <- rng_key(42L)')
L.append('  hex <- as.character(rng_bits(key, 8L, bits = 64L))')
L.append('  # strtoi() returns NA above 2^31, so fold two 16-bit halves in double')
L.append('  # arithmetic instead of parsing all 8 low hex digits at once.')
L.append('  lo <- strtoi(substr(hex, 9L, 12L), 16L) * 65536 +')
L.append('        strtoi(substr(hex, 13L, 16L), 16L)')
L.append('  expect_equal(rng_bits(key, 8L), lo)')
L.append('})')
open('/tmp/test-kat.R','w').write("\n".join(L) + "\n")
print("\n".join(L[:14]))
print("...")
print("lines:", len(L))
